require docutils<0.19 for in docs/requirements.txt
avoids ImportError: cannot import name 'ErrorString' from 'docutils.core' when using docutils 0.20.1