docs requirement mistune<2.0.0
versions of mistuen 2.x.x cause the docs to fail wit:
` AttributeError: module 'mistune' has no attribute 'BlockGrammar' `